#!/bin/bash
set -e

for s in "$@"; do
	name="$(echo "$s/" | cut -f1 -d/)"
	pri="$(echo "$s/" | cut -f2 -d/)"
	if [ -z "$name" ]; then
		out="$out ENV_CREATE($pri);"
	elif [ -z "$pri" ]; then
		out="$out ENV_CREATE(test_$name);"
	else
		out="$out ENV_CREATE_PRIORITY(test_$name, $pri);"
	fi
done

# shellcheck disable=2028
echo 'void mips_init() {
	printk("init.c:\tmips_init() is called\n");

	page_init();

	extern char exc_gen_entry[];
	asm volatile("csrw stvec, %0" : : "r"(exc_gen_entry));

	env_init();

'"$out"'

	u_long sie;
	asm volatile("csrr %0, sie" : "=r"(sie));
	printk("%016lx\n", sie);

	
	int r = sbi_set_timer(10000000);
	asm volatile("csrs sie, %0" : : "r"(SIE_STIE));
	asm volatile("csrs sstatus, %0" : : "r"(SSTATUS_SIE));


	while (1) {
	}
	panic("init.c:\tend of mips_init() reached!");
}' > include/generated/init_override.h
